# Generated by Django 4.0.5 on 2022-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0002_tweet_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/avatar')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('quote', models.TextField()),
                ('authorquote', models.CharField(blank=True, max_length=255, null=True)),
                ('instalink', models.CharField(blank=True, max_length=255, null=True)),
                ('telelink', models.CharField(blank=True, max_length=255, null=True)),
                ('gitlink', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
