# Generated by Django 4.0.5 on 2022-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0003_user_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_view',
            name='name',
        ),
        migrations.AlterField(
            model_name='user_view',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
